version: '3.8'
services:
  web:
    build: .
    command: >
       sh -c "cd server &&
             flask db upgrade &&
             gunicorn -b 0.0.0.0:5001 -w 8 app:app"
    ports:
      - 5001:5001
    environment:
      - ENV=${ENV}
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
      - SECRET_KEY=${SECRET_KEY}
      - MAIL_SERVER=${MAIL_SERVER}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USE_SSL=${MAIL_USE_SSL}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_DEFAULT_SENDER=${MAIL_DEFAULT_SENDER}
      - INTERNAL_URL=${INTERNAL_URL}
      - REDIS_URL=${REDIS_URL}
    restart: unless-stopped
    volumes:
      - ./storage:/app/server/storage
